// src/utils/languageOptions.js

const languageOptions = [
  { label: "English", code: "en" },
  { label: "Spanish", code: "es" },
  { label: "French", code: "fr" },
  { label: "German", code: "de" },
  { label: "Portuguese", code: "pt" },
  { label: "Italian", code: "it" },
  { label: "Dutch", code: "nl" },
  { label: "Flemish", code: "nl" },
  { label: "Russian", code: "ru" },
  { label: "Ukrainian", code: "uk" },
  { label: "Polish", code: "pl" },
  { label: "Romanian", code: "ro" },
  { label: "Czech", code: "cs" },
  { label: "Slovak", code: "sk" },
  { label: "Hungarian", code: "hu" },
  { label: "Bulgarian", code: "bg" },
  { label: "Greek", code: "el" },
  { label: "Turkish", code: "tr" },
  { label: "Danish", code: "da" },
  { label: "Swedish", code: "sv" },
  { label: "Norwegian", code: "no" },
  { label: "Finnish", code: "fi" },
  { label: "Estonian", code: "et" },
  { label: "Latvian", code: "lv" },
  { label: "Lithuanian", code: "lt" },
  { label: "Malay", code: "ms" },
  { label: "Indonesian", code: "id" },
  { label: "Hindi", code: "hi" },
  { label: "Japanese", code: "ja" },
  { label: "Korean", code: "ko" },
  { label: "Vietnamese", code: "vi" },
  { label: "Thai", code: "th" },
  { label: "Catalan", code: "ca" },
  { label: "Chinese", code: "zh" },
];

export default languageOptions;
